DOMAIN = "sonos_hue_sync"

CONF_SONOS_ENTITY = "sonos_entity"
CONF_LIGHT_GROUP = "light_group"
CONF_LIGHT_ENTITIES = "light_entities"
CONF_GROUP_ENTITIES = "group_entities"
CONF_MEMBER_LIGHT_ENTITIES = "member_light_entities"
CONF_COLOR_COUNT = "color_count"
CONF_PALETTE_ORDERING = "palette_ordering"
CONF_TRANSITION = "transition"
CONF_FILTER_DULL = "filter_dull"
CONF_FILTER_BRIGHT_WHITE = "filter_bright_white"
CONF_MONOCHROME_MODE = "monochrome_mode"
CONF_LOW_COLOR_HANDLING = "low_color_handling"
CONF_TRUE_GRADIENT_MODE = "true_gradient_mode"
CONF_GRADIENT_COLOR_POINTS = "gradient_color_points"
CONF_GRADIENT_ORDER_MODE = "gradient_order_mode"
CONF_CACHE = "cache"
CONF_EXPAND_GROUPS = "expand_groups"
CONF_ASSIGNMENT_STRATEGY = "assignment_strategy"

DEFAULT_COLOR_COUNT = 3
DEFAULT_PALETTE_ORDERING = "dominant_first"
DEFAULT_TRANSITION = 2
DEFAULT_FILTER_DULL = True
DEFAULT_FILTER_BRIGHT_WHITE = True
DEFAULT_MONOCHROME_MODE = "warm_neutral"
DEFAULT_LOW_COLOR_HANDLING = True
DEFAULT_TRUE_GRADIENT_MODE = False
DEFAULT_GRADIENT_COLOR_POINTS = 5
DEFAULT_GRADIENT_ORDER_MODE = "same_order"
DEFAULT_CACHE = True
DEFAULT_EXPAND_GROUPS = True
DEFAULT_ASSIGNMENT_STRATEGY = "balanced"

PALETTE_ORDERING_VIVID_FIRST = "vivid_first"
PALETTE_ORDERING_DOMINANT_FIRST = "dominant_first"
PALETTE_ORDERING_OPTIONS = [
    PALETTE_ORDERING_VIVID_FIRST,
    PALETTE_ORDERING_DOMINANT_FIRST,
]
PALETTE_ORDERING_LABELS = {
    PALETTE_ORDERING_VIVID_FIRST: "Vivid Colors First",
    PALETTE_ORDERING_DOMINANT_FIRST: "Dominant Colors First",
}

ASSIGNMENT_STRATEGY_SEQUENTIAL = "sequential"
ASSIGNMENT_STRATEGY_BALANCED = "balanced"
ASSIGNMENT_STRATEGY_ALTERNATING = "alternating"
ASSIGNMENT_STRATEGY_BRIGHTNESS = "brightness"

PLATFORMS = ["switch", "select", "number", "button", "sensor"]

SERVICE_ENABLE = "enable"
SERVICE_DISABLE = "disable"
SERVICE_APPLY_LAST_PALETTE = "apply_last_palette"
SERVICE_TEST_COLOR = "test_color"
SERVICE_EXTRACT_NOW = "extract_now"
SERVICE_TEST_RAINBOW = "test_rainbow"
SERVICE_SHOW_HELP = "show_help"

ATTR_HEX_COLORS = "hex_colors"
ATTR_RGB_COLORS = "rgb_colors"
ATTR_SOURCE_IMAGE = "source_image"
ATTR_RESOLVED_LIGHTS = "resolved_lights"
ATTR_LAST_SERVICE_DATA = "last_service_data"
ATTR_PALETTE_PREVIEW = "palette_preview"
ATTR_COLOR_COUNT_ACTUAL = "color_count_actual"

MONOCHROME_MODE_WARM_NEUTRAL = "warm_neutral"
MONOCHROME_MODE_GRAYSCALE = "grayscale"
MONOCHROME_MODE_MUTED_ACCENT = "muted_accent"
MONOCHROME_MODE_DISABLED = "disabled"


GRADIENT_ORDER_MODE_SAME = "same_order"
GRADIENT_ORDER_MODE_ROTATED = "rotated_by_light"
GRADIENT_ORDER_MODE_RANDOM = "random"
GRADIENT_ORDER_MODES = [
    GRADIENT_ORDER_MODE_SAME,
    GRADIENT_ORDER_MODE_ROTATED,
    GRADIENT_ORDER_MODE_RANDOM,
]
GRADIENT_ORDER_MODE_LABELS = {
    GRADIENT_ORDER_MODE_SAME: "Same order on every gradient light",
    GRADIENT_ORDER_MODE_ROTATED: "Offset per light",
    GRADIENT_ORDER_MODE_RANDOM: "Random order",
}

SERVICE_HEALTH_CHECK = "health_check"


CONF_MIN_BRIGHTNESS = "min_brightness"
CONF_MAX_BRIGHTNESS = "max_brightness"
CONF_GRADIENT_BRIGHTNESS = "gradient_brightness"
CONF_EXCLUDE_LIGHT_ENTITIES = "exclude_light_entities"
CONF_RESTORE_DELAY = "restore_delay"

DEFAULT_MIN_BRIGHTNESS = 30
DEFAULT_MAX_BRIGHTNESS = 255
DEFAULT_GRADIENT_BRIGHTNESS = 255
DEFAULT_EXCLUDE_LIGHT_ENTITIES = []
DEFAULT_RESTORE_DELAY = 0


CONF_ARTWORK_FALLBACK_MODE = "artwork_fallback_mode"
DEFAULT_ARTWORK_FALLBACK_MODE = "reuse_last"

ARTWORK_FALLBACK_REUSE_LAST = "reuse_last"
ARTWORK_FALLBACK_TRACK_BASED = "track_based"
ARTWORK_FALLBACK_WARM_NEUTRAL = "warm_neutral"
ARTWORK_FALLBACK_DO_NOTHING = "do_nothing"

ARTWORK_FALLBACK_MODES = [
    ARTWORK_FALLBACK_REUSE_LAST,
    ARTWORK_FALLBACK_TRACK_BASED,
    ARTWORK_FALLBACK_WARM_NEUTRAL,
    ARTWORK_FALLBACK_DO_NOTHING,
]

ARTWORK_FALLBACK_MODE_LABELS = {
    ARTWORK_FALLBACK_REUSE_LAST: "Reuse last palette",
    ARTWORK_FALLBACK_TRACK_BASED: "Track-based colors",
    ARTWORK_FALLBACK_WARM_NEUTRAL: "Warm neutral",
    ARTWORK_FALLBACK_DO_NOTHING: "Do nothing",
}


CONF_AIRPLAY_POLL_INTERVAL = "airplay_poll_interval"
DEFAULT_AIRPLAY_POLL_INTERVAL = 5


CONF_AUTO_ROTATE_COLORS = "auto_rotate_colors"
DEFAULT_AUTO_ROTATE_COLORS = False
CONF_AUTO_ROTATE_INTERVAL = "auto_rotate_interval"
DEFAULT_AUTO_ROTATE_INTERVAL = 30
MIN_AUTO_ROTATE_INTERVAL = 1
MAX_AUTO_ROTATE_INTERVAL = 60
AUTO_ROTATE_SAFETY_BUFFER_SECONDS = 2.0
