# Shared constants. Defines defaults, options, entity labels, and behavior presets used across the integration.
# brief-code-commented-build: moderate block-level comments added for maintainability.
DOMAIN = "sonos_hue_sync"

CONF_SONOS_ENTITY = "sonos_entity"
CONF_LIGHT_GROUP = "light_group"
CONF_LIGHT_ENTITIES = "light_entities"
CONF_GROUP_ENTITIES = "group_entities"
CONF_MEMBER_LIGHT_ENTITIES = "member_light_entities"
CONF_COLOR_COUNT = "color_count"
CONF_PALETTE_ORDERING = "palette_ordering"
CONF_PALETTE_COHERENCE = "palette_coherence"
CONF_TRANSITION = "transition"
CONF_FILTER_DULL = "filter_dull"
CONF_FILTER_BRIGHT_WHITE = "filter_bright_white"
CONF_COLOR_ACCURACY_MODE = "color_accuracy_mode"
CONF_MONOCHROME_MODE = "monochrome_mode"
CONF_LOW_COLOR_HANDLING = "low_color_handling"
CONF_TRUE_GRADIENT_MODE = "true_gradient_mode"
CONF_GRADIENT_COLOR_POINTS = "gradient_color_points"
CONF_GRADIENT_ORDER_MODE = "gradient_order_mode"
CONF_CACHE = "cache"
CONF_EXPAND_GROUPS = "expand_groups"
CONF_ASSIGNMENT_STRATEGY = "assignment_strategy"

DEFAULT_COLOR_COUNT = 3
DEFAULT_PALETTE_ORDERING = "dominant_first"
DEFAULT_TRANSITION = 2
DEFAULT_FILTER_DULL = True
DEFAULT_FILTER_BRIGHT_WHITE = True
DEFAULT_COLOR_ACCURACY_MODE = "natural"
DEFAULT_MONOCHROME_MODE = "warm_neutral"
DEFAULT_LOW_COLOR_HANDLING = True
DEFAULT_TRUE_GRADIENT_MODE = False
DEFAULT_GRADIENT_COLOR_POINTS = 5
DEFAULT_GRADIENT_ORDER_MODE = "same_order"
DEFAULT_CACHE = True
DEFAULT_EXPAND_GROUPS = True
DEFAULT_ASSIGNMENT_STRATEGY = "balanced"

COLOR_ACCURACY_MODE_NATURAL = "natural"
COLOR_ACCURACY_MODE_VIVID = "vivid"
COLOR_ACCURACY_MODE_ALBUM = "album_accurate"
COLOR_ACCURACY_MODE_OPTIONS = [
    COLOR_ACCURACY_MODE_NATURAL,
    COLOR_ACCURACY_MODE_VIVID,
    COLOR_ACCURACY_MODE_ALBUM,
]
COLOR_ACCURACY_MODE_LABELS = {
    COLOR_ACCURACY_MODE_NATURAL: "Natural",
    COLOR_ACCURACY_MODE_VIVID: "Vivid",
    COLOR_ACCURACY_MODE_ALBUM: "Album Accurate",
}

PALETTE_ORDERING_VIVID_FIRST = "vivid_first"
PALETTE_ORDERING_DOMINANT_FIRST = "dominant_first"
PALETTE_ORDERING_OPTIONS = [
    PALETTE_ORDERING_VIVID_FIRST,
    PALETTE_ORDERING_DOMINANT_FIRST,
]
PALETTE_ORDERING_LABELS = {
    PALETTE_ORDERING_VIVID_FIRST: "Vivid Colors First",
    PALETTE_ORDERING_DOMINANT_FIRST: "Dominant Colors First",
}


# Artwork Style is the main artistic intent selector. It maps several lower-level
# extraction controls into one friendly choice while preserving advanced controls.
CONF_ARTWORK_STYLE = "artwork_style"
ARTWORK_STYLE_AUTO = "auto"
ARTWORK_STYLE_NATURAL = "natural"
ARTWORK_STYLE_ALBUM = "album_accurate"
ARTWORK_STYLE_GRAPHIC = "graphic_poster"
ARTWORK_STYLE_PHOTOGRAPHY = "photography"
ARTWORK_STYLE_CINEMATIC = "cinematic"
ARTWORK_STYLE_SOFT = "soft_ambient"
ARTWORK_STYLE_BOLD = "bold_high_contrast"
ARTWORK_STYLE_MONOCHROME = "monochrome_accent"
# Legacy value is still accepted internally but is intentionally not exposed in the UI.
ARTWORK_STYLE_ADVANCED = "advanced_custom"
DEFAULT_ARTWORK_STYLE = ARTWORK_STYLE_AUTO
ARTWORK_STYLE_OPTIONS = [
    ARTWORK_STYLE_AUTO,
    ARTWORK_STYLE_ALBUM,
    ARTWORK_STYLE_NATURAL,
    ARTWORK_STYLE_GRAPHIC,
    ARTWORK_STYLE_PHOTOGRAPHY,
    ARTWORK_STYLE_CINEMATIC,
    ARTWORK_STYLE_SOFT,
    ARTWORK_STYLE_BOLD,
    ARTWORK_STYLE_MONOCHROME,
]
ARTWORK_STYLE_LABELS = {
    ARTWORK_STYLE_AUTO: "Auto",
    ARTWORK_STYLE_NATURAL: "Natural",
    ARTWORK_STYLE_ALBUM: "Album Accurate",
    ARTWORK_STYLE_GRAPHIC: "Graphic / Poster",
    ARTWORK_STYLE_PHOTOGRAPHY: "Photography",
    ARTWORK_STYLE_CINEMATIC: "Cinematic",
    ARTWORK_STYLE_SOFT: "Soft Ambient",
    ARTWORK_STYLE_BOLD: "Bold / High Contrast",
    ARTWORK_STYLE_MONOCHROME: "Monochrome Accent",
    ARTWORK_STYLE_ADVANCED: "Advanced / Custom",
}

CONF_AUTO_STYLE_BEHAVIOR = "auto_style_behavior"
AUTO_STYLE_BALANCED = "balanced"
AUTO_STYLE_ACCURACY = "prefer_accuracy"
AUTO_STYLE_VIVID = "prefer_vivid"
AUTO_STYLE_AMBIENT = "prefer_ambient"
DEFAULT_AUTO_STYLE_BEHAVIOR = AUTO_STYLE_BALANCED
AUTO_STYLE_BEHAVIOR_OPTIONS = [
    AUTO_STYLE_BALANCED,
    AUTO_STYLE_ACCURACY,
    AUTO_STYLE_VIVID,
    AUTO_STYLE_AMBIENT,
]
AUTO_STYLE_BEHAVIOR_LABELS = {
    AUTO_STYLE_BALANCED: "Balanced",
    AUTO_STYLE_ACCURACY: "Prefer Accuracy",
    AUTO_STYLE_VIVID: "Prefer Vivid",
    AUTO_STYLE_AMBIENT: "Prefer Ambient",
}

# Neutral Tone Handling combines white handling and black-and-white handling into
# one outcome-based control. Legacy controls remain available as Advanced / Custom.
CONF_NEUTRAL_TONE_HANDLING = "neutral_tone_handling"
NEUTRAL_TONE_NATURAL = "natural"
NEUTRAL_TONE_REDUCE_WHITES = "reduce_whites"
NEUTRAL_TONE_PRESERVE_CONTRAST = "preserve_contrast"
NEUTRAL_TONE_WARM_AMBIENT = "warm_ambient"
NEUTRAL_TONE_GRAPHIC = "graphic_poster"
NEUTRAL_TONE_ALLOW_WHITE = "allow_pure_white"
# Legacy value is still accepted internally but is intentionally not exposed in the UI.
NEUTRAL_TONE_ADVANCED = "advanced_custom"
DEFAULT_NEUTRAL_TONE_HANDLING = NEUTRAL_TONE_NATURAL
NEUTRAL_TONE_OPTIONS = [
    NEUTRAL_TONE_NATURAL,
    NEUTRAL_TONE_REDUCE_WHITES,
    NEUTRAL_TONE_PRESERVE_CONTRAST,
    NEUTRAL_TONE_WARM_AMBIENT,
    NEUTRAL_TONE_GRAPHIC,
    NEUTRAL_TONE_ALLOW_WHITE,
]
NEUTRAL_TONE_LABELS = {
    NEUTRAL_TONE_NATURAL: "Natural",
    NEUTRAL_TONE_REDUCE_WHITES: "Reduce Whites",
    NEUTRAL_TONE_PRESERVE_CONTRAST: "Preserve Contrast",
    NEUTRAL_TONE_WARM_AMBIENT: "Warm Ambient",
    NEUTRAL_TONE_GRAPHIC: "Graphic / Poster",
    NEUTRAL_TONE_ALLOW_WHITE: "Allow Pure White",
    NEUTRAL_TONE_ADVANCED: "Advanced / Custom",
}

# Palette Coherence is a universal outlier filter. It is intentionally
# option-based rather than a granular slider so the UI remains understandable.
PALETTE_COHERENCE_OFF = "off"
PALETTE_COHERENCE_BALANCED = "balanced"
PALETTE_COHERENCE_STRICT = "strict"
DEFAULT_PALETTE_COHERENCE = PALETTE_COHERENCE_BALANCED
PALETTE_COHERENCE_OPTIONS = [
    PALETTE_COHERENCE_OFF,
    PALETTE_COHERENCE_BALANCED,
    PALETTE_COHERENCE_STRICT,
]
PALETTE_COHERENCE_LABELS = {
    PALETTE_COHERENCE_OFF: "Off",
    PALETTE_COHERENCE_BALANCED: "Balanced",
    PALETTE_COHERENCE_STRICT: "Strict",
}

ASSIGNMENT_STRATEGY_SEQUENTIAL = "sequential"
ASSIGNMENT_STRATEGY_BALANCED = "balanced"
ASSIGNMENT_STRATEGY_ALTERNATING = "alternating"
ASSIGNMENT_STRATEGY_BRIGHTNESS = "brightness"

PLATFORMS = ["switch", "select", "number", "button", "sensor"]

SERVICE_ENABLE = "enable"
SERVICE_DISABLE = "disable"
SERVICE_APPLY_LAST_PALETTE = "apply_last_palette"
SERVICE_TEST_COLOR = "test_color"
SERVICE_EXTRACT_NOW = "extract_now"
SERVICE_TEST_RAINBOW = "test_rainbow"
SERVICE_SHOW_HELP = "show_help"

ATTR_HEX_COLORS = "hex_colors"
ATTR_RGB_COLORS = "rgb_colors"
ATTR_SOURCE_IMAGE = "source_image"
ATTR_RESOLVED_LIGHTS = "resolved_lights"
ATTR_LAST_SERVICE_DATA = "last_service_data"
ATTR_PALETTE_PREVIEW = "palette_preview"
ATTR_COLOR_COUNT_ACTUAL = "color_count_actual"

MONOCHROME_MODE_WARM_NEUTRAL = "warm_neutral"
MONOCHROME_MODE_GRAYSCALE = "grayscale"
MONOCHROME_MODE_MUTED_ACCENT = "muted_accent"
MONOCHROME_MODE_DISABLED = "disabled"


GRADIENT_ORDER_MODE_SAME = "same_order"
GRADIENT_ORDER_MODE_ROTATED = "rotated_by_light"
GRADIENT_ORDER_MODE_RANDOM = "random"
GRADIENT_ORDER_MODE_DARK_TO_LIGHT = "dark_to_light"
GRADIENT_ORDER_MODE_LIGHT_TO_DARK = "light_to_dark"
GRADIENT_ORDER_MODES = [
    GRADIENT_ORDER_MODE_SAME,
    GRADIENT_ORDER_MODE_ROTATED,
    GRADIENT_ORDER_MODE_RANDOM,
    GRADIENT_ORDER_MODE_DARK_TO_LIGHT,
    GRADIENT_ORDER_MODE_LIGHT_TO_DARK,
]
GRADIENT_ORDER_MODE_LABELS = {
    GRADIENT_ORDER_MODE_SAME: "Same Order",
    GRADIENT_ORDER_MODE_ROTATED: "Offset",
    GRADIENT_ORDER_MODE_RANDOM: "Random Order",
    GRADIENT_ORDER_MODE_DARK_TO_LIGHT: "Dark to Light",
    GRADIENT_ORDER_MODE_LIGHT_TO_DARK: "Light to Dark",
}


# Gradient Neutral Suppression controls only native Hue gradient lights.
# It prevents gray/black/near-white gradient anchors from becoming visible
# white on Hue gradient hardware when strong non-neutral colors are available.
CONF_GRADIENT_NEUTRAL_SUPPRESSION = "gradient_neutral_suppression"
GRADIENT_NEUTRAL_SUPPRESSION_OFF = "off"
GRADIENT_NEUTRAL_SUPPRESSION_AUTO = "auto"
GRADIENT_NEUTRAL_SUPPRESSION_STRONG = "strong"
GRADIENT_NEUTRAL_SUPPRESSION_KEEP_ARTWORK_WHITES = "keep_artwork_whites"
DEFAULT_GRADIENT_NEUTRAL_SUPPRESSION = GRADIENT_NEUTRAL_SUPPRESSION_AUTO
GRADIENT_NEUTRAL_SUPPRESSION_OPTIONS = [
    GRADIENT_NEUTRAL_SUPPRESSION_OFF,
    GRADIENT_NEUTRAL_SUPPRESSION_AUTO,
    GRADIENT_NEUTRAL_SUPPRESSION_STRONG,
    GRADIENT_NEUTRAL_SUPPRESSION_KEEP_ARTWORK_WHITES,
]
GRADIENT_NEUTRAL_SUPPRESSION_LABELS = {
    GRADIENT_NEUTRAL_SUPPRESSION_OFF: "Off",
    GRADIENT_NEUTRAL_SUPPRESSION_AUTO: "Auto",
    GRADIENT_NEUTRAL_SUPPRESSION_STRONG: "Strong",
    GRADIENT_NEUTRAL_SUPPRESSION_KEEP_ARTWORK_WHITES: "Keep Whites Only When Present",
}

SERVICE_HEALTH_CHECK = "health_check"


CONF_MIN_BRIGHTNESS = "min_brightness"
CONF_MAX_BRIGHTNESS = "max_brightness"
CONF_GRADIENT_BRIGHTNESS = "gradient_brightness"
CONF_EXCLUDE_LIGHT_ENTITIES = "exclude_light_entities"
CONF_RESTORE_DELAY = "restore_delay"

DEFAULT_MIN_BRIGHTNESS = 30
DEFAULT_MAX_BRIGHTNESS = 255
DEFAULT_GRADIENT_BRIGHTNESS = 255
DEFAULT_EXCLUDE_LIGHT_ENTITIES = []
DEFAULT_RESTORE_DELAY = 0


CONF_ARTWORK_FALLBACK_MODE = "artwork_fallback_mode"
DEFAULT_ARTWORK_FALLBACK_MODE = "reuse_last"

ARTWORK_FALLBACK_REUSE_LAST = "reuse_last"
ARTWORK_FALLBACK_TRACK_BASED = "track_based"
ARTWORK_FALLBACK_WARM_NEUTRAL = "warm_neutral"
ARTWORK_FALLBACK_DO_NOTHING = "do_nothing"

ARTWORK_FALLBACK_MODES = [
    ARTWORK_FALLBACK_REUSE_LAST,
    ARTWORK_FALLBACK_TRACK_BASED,
    ARTWORK_FALLBACK_WARM_NEUTRAL,
    ARTWORK_FALLBACK_DO_NOTHING,
]

ARTWORK_FALLBACK_MODE_LABELS = {
    ARTWORK_FALLBACK_REUSE_LAST: "Reuse last palette",
    ARTWORK_FALLBACK_TRACK_BASED: "Track-based colors",
    ARTWORK_FALLBACK_WARM_NEUTRAL: "Warm neutral",
    ARTWORK_FALLBACK_DO_NOTHING: "Do nothing",
}


CONF_AIRPLAY_POLL_INTERVAL = "airplay_poll_interval"
DEFAULT_AIRPLAY_POLL_INTERVAL = 5


CONF_AUTO_ROTATE_COLORS = "auto_rotate_colors"
DEFAULT_AUTO_ROTATE_COLORS = False
CONF_AUTO_ROTATE_INTERVAL = "auto_rotate_interval"
DEFAULT_AUTO_ROTATE_INTERVAL = 30
MIN_AUTO_ROTATE_INTERVAL = 1
MAX_AUTO_ROTATE_INTERVAL = 60
AUTO_ROTATE_SAFETY_BUFFER_SECONDS = 2.0

CONF_WHITE_HANDLING = "white_handling"
WHITE_HANDLING_CONTEXTUAL = "suppress_when_color_exists"
WHITE_HANDLING_ALWAYS_FILTER = "always_filter"
WHITE_HANDLING_ALLOW = "allow_whites"
DEFAULT_WHITE_HANDLING = WHITE_HANDLING_CONTEXTUAL
WHITE_HANDLING_OPTIONS = [
    WHITE_HANDLING_CONTEXTUAL,
    WHITE_HANDLING_ALWAYS_FILTER,
    WHITE_HANDLING_ALLOW,
]
WHITE_HANDLING_LABELS = {
    WHITE_HANDLING_CONTEXTUAL: "Natural",
    WHITE_HANDLING_ALWAYS_FILTER: "Reduce Whites",
    WHITE_HANDLING_ALLOW: "Allow Whites",
}

CONF_WHITE_FILTER_STRENGTH = "white_filter_strength"
WHITE_FILTER_STRENGTH_GENTLE = "gentle"
WHITE_FILTER_STRENGTH_BALANCED = "balanced"
WHITE_FILTER_STRENGTH_STRONG = "strong"
DEFAULT_WHITE_FILTER_STRENGTH = WHITE_FILTER_STRENGTH_BALANCED
WHITE_FILTER_STRENGTH_OPTIONS = [
    WHITE_FILTER_STRENGTH_GENTLE,
    WHITE_FILTER_STRENGTH_BALANCED,
    WHITE_FILTER_STRENGTH_STRONG,
]
WHITE_FILTER_STRENGTH_LABELS = {
    WHITE_FILTER_STRENGTH_GENTLE: "Gentle",
    WHITE_FILTER_STRENGTH_BALANCED: "Balanced",
    WHITE_FILTER_STRENGTH_STRONG: "Strong",
}

CONF_ROTATION_MODE = "rotation_mode"
ROTATION_MODE_TRACK_CHANGE = "track_change"
ROTATION_MODE_OFF = "off"
ROTATION_MODE_AUTO = "auto_rotate"
ROTATION_MODE_TRACK_AND_AUTO = "track_change_and_auto_rotate"
DEFAULT_ROTATION_MODE = ROTATION_MODE_TRACK_CHANGE
ROTATION_MODE_OPTIONS = [
    ROTATION_MODE_TRACK_CHANGE,
    ROTATION_MODE_OFF,
    ROTATION_MODE_AUTO,
    ROTATION_MODE_TRACK_AND_AUTO,
]
ROTATION_MODE_LABELS = {
    ROTATION_MODE_OFF: "Off",
    ROTATION_MODE_TRACK_CHANGE: "On Track Change",
    ROTATION_MODE_AUTO: "Continuous",
    ROTATION_MODE_TRACK_AND_AUTO: "Track Change and Continuous",
}

# User-facing palette tuning controls.
# Color Purity controls how closely extracted colors follow the album art:
# 0 favors only strong saturated colors; 100 preserves the album palette most faithfully.
CONF_COLOR_PURITY = "color_purity"
DEFAULT_COLOR_PURITY = 65

# Color Purity Preset keeps the old numeric color-purity behavior while
# replacing the confusing slider with named choices in the UI. The string
# values intentionally remain numeric so existing palette code and old saved
# custom values continue to work without a migration.
COLOR_PURITY_PRESET_SOFT = "80"
COLOR_PURITY_PRESET_BALANCED = "65"
COLOR_PURITY_PRESET_VIVID = "35"
COLOR_PURITY_PRESET_ALBUM = "90"
COLOR_PURITY_PRESET_BOLD = "20"
COLOR_PURITY_PRESET_CUSTOM = "custom"
COLOR_PURITY_PRESET_OPTIONS = [
    COLOR_PURITY_PRESET_BALANCED,
    COLOR_PURITY_PRESET_ALBUM,
    COLOR_PURITY_PRESET_SOFT,
    COLOR_PURITY_PRESET_VIVID,
    COLOR_PURITY_PRESET_BOLD,
]
COLOR_PURITY_PRESET_LABELS = {
    COLOR_PURITY_PRESET_BALANCED: "Balanced",
    COLOR_PURITY_PRESET_ALBUM: "Album Accurate",
    COLOR_PURITY_PRESET_SOFT: "Soft / Ambient",
    COLOR_PURITY_PRESET_VIVID: "Vivid",
    COLOR_PURITY_PRESET_BOLD: "Bold / High Contrast",
    COLOR_PURITY_PRESET_CUSTOM: "Custom / Existing",
}

# White Suppression controls white/light-neutral suppression separately from color purity.
# 0 preserves whites; 100 strongly suppresses white/light gray tones.
CONF_WHITE_LEVEL = "white_level"
DEFAULT_WHITE_LEVEL = 50
