
DOMAIN = "sonos_hue_sync"
CONF_SONOS_ENTITY = "sonos_entity"
CONF_LIGHT_GROUP = "light_group"
CONF_COLOR_COUNT = "color_count"
CONF_TRANSITION = "transition"
CONF_FILTER_DULL = "filter_dull"
CONF_CACHE = "cache"
CONF_ENABLED = "enabled"
CONF_HUE_DIRECT = "hue_direct"
